### ISSUE TITLE
Typo in plugin name

### ISSUE THREAD

**Issue by siebird** [helloswish/securi-cache-clear#1]
Hey, Chad. 

We just installed this, and I thought I was losing my mind as I searched the plugin store for `Sucuri`, and nothing showed up.  I do the same thing all the time and type in `securi` in my browser looking for their site.

**Comment by chadcrowell** [comment]
Wild. I never noticed the U. I think I'm going to have to submit an entirely new version of the plugin to fix this... thanks for the heads up. Hope things are good for you!

**Comment by siebird** [comment]
It might be good to keep the typo version in the keywords for the plugin store.

**Comment by chadcrowell** [comment]
[New plugin with correct name](https://plugins.craftcms.com/sucuri-cache-clear). Thanks for the assist Austin.
